default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>

development:
  secret_key_base: blabla
  secret_token: blabla

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
